# Can override the default connection name with an environment variable as follows
#export SNOWFLAKE_DEFAULT_CONNECTION_NAME="default"

[default]
account = "ri46886.central-india.azure"
user = "ISHAANJINDAL"
password = "Ishaan@1234567"
role = "ACCOUNTADMIN"
warehouse = "COMPUTE_WH"
database = "HOL_DB"
schema = "ANALYTICS"
